### ISSUE TITLE
How to build app use  Normal edition , not SDK edition

### ISSUE THREAD

**Issue by finscn** [nwjs/nw-builder#365]
How to build app use  Normal edition , not SDK edition ?

Now nw-builder always downloads and uses SDK .

I can't set  "flavor"  in Command Line.

**Comment by finscn** [comment]
the flavor is always "sdk"

https://github.com/nwjs/nw-builder/blob/master/lib/index.js#L36

**Comment by DblK** [comment]
The "sdk" flavor that you pointed out is only for the [default value](https://github.com/nwjs/nw-builder/blob/master/lib/index.js#L26).

As all options, you can override them by setting another value; in your case "normal".
It's the same way as your can specify a specific version not "latest" and/or a target platform.

I hope I am clear enough.

**Comment by finscn** [comment]
@DblK  clear enough.   I know how to do that in JS (node) , but 

I can't  set "flavor" in Command Line.

**Comment by GendelfLugansk** [comment]
I develop with [brzpegasus/ember-cli-nwjs](https://github.com/brzpegasus/ember-cli-nwjs), which uses nw-builder to package an app, and I'm also facing the same issue: ``flavor`` option is ignored. Tried 'nacl' instead of 'normal', but result is the same.

**Comment by adam-lynch** [comment]
We'll fix this. I'd love if one of you wanted to submit a pull-request though 😀

**Comment by finscn** [comment]
@adam-lynch , ok ,  I'll try to do it  in this weekend.

**Comment by HWliao** [comment]
i use the nw-builder@3.1.0,commandline:nwbuild -p win32 -v 0.17.3 --flavor normal .
finally it use the sdk...

**Comment by MichDanD** [comment]
@nbjahan That worked for me. Thanks.

After adding `flavor: argv.flavor || 'sdk',` to `nw-builder\bin\nwbuild` , I run a build script using the module:

File: `buildapp.js`

```javascript
var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
  files: ['./app/**'], 
  platforms: ['win32', 'linux64'],
  flavor: 'normal', // The 'edition' argument
  version: '0.17.5'
});

nw.build().then(function () {
  console.log('all done!');
}).catch(function (error) {
  console.error(error);
});
```

**Comment by adam-lynch** [comment]
Fixed in v3.1.1. Thanks all!

**Comment by maikonmatheus** [comment]
You forgot to include the "--flavor normal" flag in the docs and CLI help.

![image](https://user-images.githubusercontent.com/24308369/62841116-d1004a80-bc7a-11e9-85c4-226e22338c0b.png)
